### PR TITLE
workaround sporadically missing apt-src on Debian

### PR DESCRIPTION
**Pull request by dirk-thomas**
Workaround for #369.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Currently ros-infrastructure/buildfarm_deployment#145 is blocking this to be tested.

**Comment by mikaelarguedas** [comment]
@dirk-thomas this can be tested now that https://github.com/ros-infrastructure/buildfarm_deployment/issues/145 is resolved

**Comment by dirk-thomas** [comment]
All recently built Lunar Debian Stretch jobs (for amd64 as well as armv8) finished without any of the builds failing with this problem. Therefore I am leaning to not merge this PR and close it (until we see the problem again).

**Comment by mikaelarguedas** [comment]
Sounds good to me, almost done rebuilding all the Stretch packages and all is green so far

**Comment by dirk-thomas** [comment]
This has failed again for Debian Jessie armv8 (http://build.ros.org/view/Kbin_djv8_dJv8/job/Kbin_djv8_dJv8__depth_image_proc__debian_jessie_arm64__binary/35/console). Since it hasn't happened for Stretch in the past rebuild but does happen for Jessie maybe this should be updated to only apply the workaround on Jessie?

**Comment by tfoote** [comment]
I see you reopened this. For the record I'm seeing about 10-20 instances of this per day over the weekend.

**Comment by dirk-thomas** [comment]
Indeed, I took care of manually retriggering all of them for the sync.

Did you see them only on Jessie (that's what the patch targets now) or also any on Stretch or other platforms?

**Comment by tfoote** [comment]
Searching the notifications I only see them on Jessie armv8 since Feb 16th. 
Before that I see both Jessie amd64 and armv8.

These errors appear to have started Jan 24th. 
I'm guessing the Jessie amd64

**Pull request merged**
