### PR TITLE
add doc about Jenkins API token

### PR DESCRIPTION
**Pull request by dirk-thomas**
As suggested in https://github.com/ros-infrastructure/ros_buildfarm/pull/276#issuecomment-204068879

### CODE REVIEW

**Comment by dhood** [comment]
Can we change the example to use DEFAULT like https://github.com/dhood/ros_buildfarm/commit/48cb947d335c91a92be34497feedf9d4757cc365 ?
Sorry to drag this on since it's such low-priority, but this is what I would have needed in the documentation to prevent opening https://github.com/ros-infrastructure/ros_buildfarm/issues/275 (I thought it was a generic .ini that needed to be changed)

**Comment by dirk-thomas** [comment]
I would rather not use `[DEFAULT]` in the example but keep the specific host. I think using a specific host implicitly documents the configuration and what it is used for. Otherwise when looking at the file later it is unclear from the file content alone.

**Comment by dhood** [comment]
good point. https://github.com/dhood/ros_buildfarm/commit/f66b6790f23c46e8b7123329a8beb66165218444?

**Comment by dhood** [comment]
good point. https://github.com/dhood/ros_buildfarm/commit/ab5319d8948f36e660cea7875489af40647901f6? if not, no problem. it can probably be figured out from the new information now

**Comment by dirk-thomas** [comment]
Since the whole documentation doesn't contain the term "test farm" I would rather not mention it in that paragraph.

**Comment by dhood** [comment]
ok no problem

**Pull request merged**
