### PR TITLE
Pin pyparsing 2.4.7 for Python 3.4 and 2.7 Travis CI jobs.

### PR DESCRIPTION
**Pull request by hidmic**
Precisely what the title says. Let's see if Travis likes it.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Please add comments why that specific version is being installed.

**Comment by hidmic** [comment]
> Please add comments why that specific version is being installed.

PTAL!

**Comment by dirk-thomas** [comment]
Nitpick: a single link (https://github.com/pyparsing/pyparsing/blob/72f2c5a67b4a26f584104b9ff63e1f272f54c5df/CHANGES#L5-L9) looks sufficient to me instead of two.

**Comment by hidmic** [comment]
@dirk-thomas done

**Pull request merged**
