### PR TITLE
Allow status page jobs to run on any agent.

### PR DESCRIPTION
**Pull request by tfoote**
The status pages jobs query the public api of the repo for status and upload to a specific non-overlapping scope of files. The uploads are managed by the ssh publisher with the credentials on the master already so they will work on any agent.

With the number of status jobs and reconfigure jobs we are actually almost at 100% duty cycle for the agent_on_master instance. Allowing these to parallelize will lower the load on the master instance. It will also allow more prompt performance of the status and reconfigure jobs.

This is a rework of #327 That was closed due to incorrect logic in https://github.com/ros-infrastructure/ros_buildfarm/issues/331#issuecomment-251174703 the sync jobs run on the repository not the master (or even agent_on_master) so single threading this does not provide any protections.

Time and resources on the agents are cheaper. If anything I might even propose removing the agent_on_master to leave it available for the reconfigure and trigger jobs. These jobs run quickly so would not starve any of the other builds. And if anything will allow the master to have less resource contention which might actually increase throughput as jobs can be dispatched more effectively without having one process dedicated to generating the status pages. 

Here's a successful build on `buildagent` http://build.ros.org/job/Krel_release-status-page/23650/console

### CODE REVIEW

**Comment by tfoote** [comment]
I'm looking at this because the master was unresponsive while debugging https://github.com/ros-infrastructure/ros_buildfarm_config/pull/167

The master was giving 502 responses to configuration updates. 

It recovered but after the recovery the temporary buildagent I'm using for rosindex had gone offline: http://build.ros.org/computer/agent-eff13541/

There were also some unusual changes in executor availabilty that likely is correlated. As well as a precipitous failure rate.

Screenshot from 2020-04-24 18-34-02

**Comment by nuclearsandwich** [comment]
Do any of these status jobs overlap such that parallel builds may interfere with eachother?

Are the jobs properly configured not to run two instances of the same status job at the same time?

**Comment by tfoote** [comment]
> Do any of these status jobs overlap such that parallel builds may interfere with eachother?

They are all read only on the repositories. They will push one unique html file and one unique yaml file. Each class copies up the css and js into a shared place. It currently overwrites the same content every time. The file system can handle the multiple incoming copies without corrupting the files.

> Are the jobs properly configured not to run two instances of the same status job at the same time?

Yes that's on by default for non-parameterized jobs.

**Comment by nuclearsandwich** [comment]
Just approved but also thought of one last question which is where do these jobs land priority-wise? I don't think they'll ever be starved out since they can always run on the agent-on-master but we should probably ensure they don't shut out other buildagent jobs when there's a low agent count.

**Comment by tfoote** [comment]
They only take ~20 seconds each. With 16 of them on the farm running every 15 minutes they will take up approximately 1/3 of a single executor. Or on our standard build machines with 4 executors ~8.3% of a lone machine.

**Pull request merged**
