### PR TITLE
Docker api

### PR DESCRIPTION
**Pull request by ruffsl**
Adding --rm to docker run command in templates,
should help ease troubles with the docker reaper.

### CODE REVIEW

**Comment by tfoote** [comment]
LGTM 

We never reattach to the containers so we might as well clean them up immediately instead of leaving them on the disk. This hopefully will help with the problem of memory growth when the cleanup script is invoked by having less in the docker databases. 

@dirk-thomas can you review as well. Then we can turn a large batch over and see if it helps.

**Comment by dirk-thomas** [comment]
Does this also imply removing the images used by the container?

**Comment by tfoote** [comment]
No this only clears the containers.
​

**Comment by dirk-thomas** [comment]
How does removing the container impact the storage size then?

**Comment by tfoote** [comment]
It doesn't significantly effect the storage size. Containers are typically under 100K in size.

**Comment by dirk-thomas** [comment]
Sounds like a minor change then. Let's go ahead and see if it brings any advantage.

**Pull request merged**
