### PR TITLE
use colcon-parallel-executor during build

### PR DESCRIPTION
**Pull request by dirk-thomas**
And as a consequence output progress only after each package has finished.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Out of curiosity: what's the interaction here with the nr of executors as configured for a particular role in the buildfarm?

**Comment by dirk-thomas** [comment]
The parallel executor will build as many packages in parallel as there are CPU cores reported. It also considers the `sched_getaffinity` (when available, see colcon/colcon-parallel-executor#17) to limit the count further.

That is beside the already used default behavior of using the maximum number of threads within a package based on the CPU core count.

**Comment by gavanderhoorn** [comment]
> That is beside the already used default behavior of using the maximum number of threads within a package based on the CPU core count.

so the nr of configured executors in the `buildfarm_deployment_config` doesn't really influence a colcon build anyway, if I understand you correctly?

Is that desirable? If I have a 4 core machine and have 3 executors configured, would colcon try to start 3 parallel jobs for all builds started?

**Comment by dirk-thomas** [comment]
> If I have a 4 core machine and have 3 executors configured, would colcon try to start 3 parallel jobs for all builds started?

Correct, that is how colcon builds have been working for the past years.

> Is that desirable?

It depends. One alternative would be to implement the job server protocol to limit the number of threads across packages.

**Comment by gavanderhoorn** [comment]
> > Is that desirable?
> 
> It depends. One alternative would be to implement the job server protocol to limit the number of threads across packages.

As a buildfarm administrator I would not like it if a single job could use all cores I've assigned to executors in a single job. That would seem to defeat the purpose of being able to configure the nr of executors in the first place.

(not sure whether CMI also does this btw)

**Comment by clalancette** [comment]
> As a buildfarm administrator I would not like it if a single job could use all cores I've assigned to executors in a single job. That would seem to defeat the purpose of being able to configure the nr of executors in the first place.

Yes and no.  In my experience, there are definitely times in a build where having multiple executors is helpful, even if each one could potentially use all of the cores.  I'm generally thinking of message packages (where we spend some time stuck in a single python process, generating code that we'll build in parallel later), and large links (where we are waiting for a final executable link).  In both of those cases, it is helpful to have multiple executors.

I'll also point out that by default, CMake invokes `make` with a `-l` parameter, so while it is true that one executor could hog all of the available resources, it shouldn't be the case that you go above the maximum load (at least, not for too long).

**Comment by dirk-thomas** [comment]
@cottsay I am going to remove your commit 01aa1c61750c9343a95b23821b0f0e0687d6ee7e since it actually changes the order to not be alphabetical.

**Comment by cottsay** [comment]
> @cottsay I am going to revert your commit [01aa1c6](https://github.com/ros-infrastructure/ros_buildfarm/commit/01aa1c61750c9343a95b23821b0f0e0687d6ee7e) since it actually changes the order to not be alphabetical.

Note to self: `catkin` != `colcon`. Same number of letters, start and end with the same letters, but not the same.

I'm the worst :stuck_out_tongue: Thanks for fixing it.

**Pull request merged**
