### PR TITLE
fix url and make operation atomic

### LINKED ISSUE #237: Jobs Failing on ccache Download
The build farm curls ccache from samba.org, and this step seems to be failing. For an example of a failed build, see http://build.ros.org/job/Jbin_uV64__swri_geometry_util__ubuntu_vivid_amd64__binary/8/console

### PR DESCRIPTION
**Pull request by tfoote**
Fixes #237

### CODE REVIEW

**Comment by dirk-thomas** [comment]
+1

**Comment by tfoote** [comment]
tested here passing ccache installation: http://build.ros.org/job/Jbin_uV64__swri_geometry_util__ubuntu_vivid_amd64__binary/9/console

**Comment by dirk-thomas** [comment]
Please revert the manual configuration change of that job.

**Comment by dirk-thomas** [comment]
Related to #216.

**Pull request merged**
