### PR TITLE
Merge the changes from Xenial into master.

### PR DESCRIPTION
**Pull request by nuclearsandwich**
Rebase of https://github.com/ros-infrastructure/ros_buildfarm/pull/479 to drop the xenial branch reference.

GitHub can retarget a PR but can't adjust the HEAD branch. Keeping the xenial branch as-is in order to avoid race conditions with the automatic reconfigure on the buildfarm.

Edit: Added merge opinion from first PR.

IMO this pull request should either be fast-forwarded or regular merged but not squashed as commit tidying was performed in the xenial-targeted PRs.

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
To merge this I want to dry run reconfiguring the farm so I'm saving it for tomorrow morning.

**Comment by dirk-thomas** [comment]
Blocked on #482 for now.

**Comment by nuclearsandwich** [comment]
Once https://github.com/ros-infrastructure/ros_buildfarm/pull/486 merges I can rebase this PR to include it and #482 and it will be ready to merge once CI is green. I'm waiting to do the actual merge and update until Thursday morning after I've landed on the ground and had a night's sleep.

**Comment by nuclearsandwich** [comment]
This has been rebased onto the latest master and is undergoing CI.

I can't dry-run and post a diff from the airport due to connection unreliability. If anyone would like to review the diff before its deployed please let me know ASAP.

If you're able to operate the dry run then you'll be able to do so today. Otherwise it will have to wait for tomorrow morning when I get online. If no one registers intent to review the diff, I'll self-review tomorrow morning before committing the changes.

**Comment by nuclearsandwich** [comment]
@mikaelarguedas here's a gist of the diff against the buildfarm. https://gist.github.com/nuclearsandwich/e772b542327afaa7e8b1799b6d30e315

I used the following script to find filter out the frequent and expected diff lines and find interesting bits.
```bash
egrep '^    (\+|-)' *.diff | egrep -v '(\+\+\+ new config|--- remote config|plugin="PrioritySorter|plugin="git|plugin="script-security|-b master| -b xenial|<name>master|<name>xenial|<daysToKeep>|<publishers />)'
```

and got the following:
```
    +reconfigure_job_names &lt;&lt; "Kdev_dj_reconfigure-jobs"                                                                                                                                                                                                                 
    -python3 -u $WORKSPACE/ros_buildfarm/scripts/status/run_release_compare_page_job.py https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml kinetic indigo jade --distribution-repository-urls http://repositories.ros.org/ubuntu/building --distribution-repository-key-files $WORKSPACE/keys/0.key --dockerfile-dir $WORKSPACE/docker_generate_compare_page
    +python3 -u $WORKSPACE/ros_buildfarm/scripts/status/run_release_compare_page_job.py https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml kinetic indigo --distribution-repository-urls http://repositories.ros.org/ubuntu/building --distribution-repository-key-files $WORKSPACE/keys/0.key --dockerfile-dir $WORKSPACE/docker_generate_compare_page
    -python3 -u $WORKSPACE/ros_buildfarm/scripts/status/run_release_compare_page_job.py https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml lunar indigo jade kinetic --distribution-repository-urls http://repositories.ros.org/ubuntu/building --distribution-repository-key-files $WORKSPACE/keys/0.key --dockerfile-dir $WORKSPACE/docker_generate_compare_page
    +python3 -u $WORKSPACE/ros_buildfarm/scripts/status/run_release_compare_page_job.py https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml lunar indigo kinetic --distribution-repository-urls http://repositories.ros.org/ubuntu/building --distribution-repository-key-files $WORKSPACE/keys/0.key --dockerfile-dir $WORKSPACE/docker_generate_compare_page
```

The last two +/- pairs are removing jade from script argument lists but I'm still looking into the reconfigure_job_names change.

**Comment by dirk-thomas** [comment]
> I'm still looking into the reconfigure_job_names change.

This is coming from a new build file which was recently added (ros-infrastructure/ros_buildfarm_config#100).

**Comment by nuclearsandwich** [comment]
> This is coming from a new build file which was recently added (ros-infrastructure/ros_buildfarm_config#100).

Ah, thanks. Are the `&lt;` escapes expected and desired there?

**Comment by dirk-thomas** [comment]
> Are the `&lt;` escapes expected and desired there?

Yes, since the text is within an XML tag it needs to escape `<` characters.

**Comment by mikaelarguedas** [comment]
Is the `+  <publishers />` expected in `kinetic_failing-jobs` ? if so is it present in the other failing jobs configs?

**Comment by nuclearsandwich** [comment]
> Is the + <publishers /> expected in kinetic_failing-jobs ? if so is it present in the other failing jobs configs?

This adds it to the kinetic and lunar jobs. It's already/still in the indigo job from when I saved the config in the webUI to check this job type for changes.

**Pull request merged**
