### PR TITLE
use template variable for unix start time

### PR DESCRIPTION
**Pull request by wjwwood**
Follow up to https://github.com/ros-infrastructure/ros_buildfarm/pull/299/files/9e051679a3fa3e992352b04c52fc7d28018909c4#r64372539

### CODE REVIEW

**Comment by dirk-thomas** [comment]
I would suggest to only pass a single `start_time = time.time()` into the template. The template can then use the raw time as well as derive a local string representation from that.

**Comment by wjwwood** [comment]
Why? Is the goal to minimize the number of template variables or the number of times we get the current time? In both cases, it doesn't seem worth the extra work...

**Comment by dirk-thomas** [comment]
The arguments passed between the "controller" and the "view" is considered to be the interface. And commonly the goal is to minimize the interface of two separate components since it increases decoupling.

**Comment by wjwwood** [comment]
I don't think we should do more work in the view to reduce the variables sent from the controller. If we send just the `time.time()` timestamp we need to create the other (`time.localtime()`) with it in each of the views.

I'm not convinced this pr needs to be changed, but feel free to add more commits if you want.

**Comment by dirk-thomas** [comment]
I have added 9328cfe0b8b3988a5e0ea4625ab3bdef9ff2edc4 to this PR. @wjwwood Does that look ok to you?

**Comment by wjwwood** [comment]
👍

**Pull request merged**
