### PR TITLE
readd flake8_docstrings, add flake8_class_newline

### PR DESCRIPTION
**Pull request by cottsay**
Looks like this regressed when changes came from machines without the plugins installed.

I added them to the test requirements so that it doesn't happen again.

### CODE REVIEW

**Comment by cottsay** [comment]
There are more plugins that we commonly have installed that we've regressed on. I'm going to make a single PR to fix them all since they'll have merge conflicts.

**Comment by dirk-thomas** [comment]
This repo hasn't been using `flake8-docstrings` until. Why add it now?

**Comment by cottsay** [comment]
> This repo hasn't been using flake8-docstrings. Why add it now?

When I run `python3 setup.py pytest` on my local machine, which has the plugin installed, I get the errors. I'd really rather not uninstall plugins to get test results locally.

**Comment by cottsay** [comment]
Also, there are numerous `noqa: D107` markers already present, which leads me to believe that it was compliant at some point.

**Comment by dirk-thomas** [comment]
Please update the title to reflect the actual change: add additional `flake8` plugins.

My remaining question: why exactly those two plugins only? Why not more (like all the ones we use in ROS 2)?

**Comment by cottsay** [comment]
> why exactly those two plugins only? Why not more?

I fixed the `docstrings` violations in #611, so that was clearly a regression. For `class_newline`, the package was already in compliance before I regressed it starting in #590 

I'd love to fix the `builtins`, `comprehensions`, and `quotes` failures, but I don't have time right now. So I took care of the regressions, which happen to be the plugins I have installed as system packages.

**Comment by dirk-thomas** [comment]
Do the plugins need to be listed here: https://github.com/ros-infrastructure/ros_buildfarm/blob/cb44a4b81779c7ec2b383698ec88ad7c3e75e354/.travis.yml#L50

**Pull request merged**
