### PR TITLE
add magic docker fix env var

### PR DESCRIPTION
**Pull request by dirk-thomas**
Fixes http://build.ros.org/view/Kbin_dj_dJ64/job/Kbin_dj_dJ64__mvsim__debian_jessie_amd64__binary/52/

No questions asked :zipper_mouth_face:

### CODE REVIEW

**Comment by tfoote** [comment]
It's using the solution in https://github.com/docker/docker/issues/14203

Unfortunately the change seems to be not a fix, but just a workaround which changes the hash and forces docker to run again. And does not prevent the bug.  We have a occurrence here: http://build.ros.org/view/Kbin_uX32/job/Ksrc_uX__camera_info_manager__ubuntu_xenial__source/

And this is also related to the older bug #337

**Comment by dirk-thomas** [comment]
You might want to try a different value for the dummy variable (or removing it) for the stuck job to pass. I assume you mean http://build.ros.org/view/Kbin_uX32/job/Kbin_uX32__camera_info_manager__ubuntu_xenial_i386__binary/ ?

**Comment by tfoote** [comment]
Yeah, that's the job I meant to link to. Yes, I think that changing the dummy variable's length can work around the problem as it seems to be an issue of the json representation length and ending on/near a newline. Adding the env variable seems to be a convenient way to not effect the build but change the encoded json length.

**Comment by dirk-thomas** [comment]
Reverted in 97e82ac0f35d2c8b2e8d673bf698484892008b3b. A custom patch needs to be applied to each failing job.

**Comment by tfoote** [comment]
There were a bunch of instances of this in our rebuild. 

I've recreated the branch docker_fix_env_var and manually triggered all the ones I found: 
 * http://build.ros.org/view/Kbin_dj_dJ64/job/Kbin_dj_dJ64__mvsim__debian_jessie_amd64__binary/
 * http://build.ros.org/view/Kbin_djv8_dJv8/job/Kbin_djv8_dJv8__mvsim__debian_jessie_arm64__binary/
 * http://build.ros.org/view/Kbin_uX32/job/Kbin_uX32__diagnostic_aggregator__ubuntu_xenial_i386__binary/
 * http://build.ros.org/view/Kbin_uW64/job/Kbin_uW64__control_toolbox__ubuntu_wily_amd64__binary/
 * http://build.ros.org/view/Jbin_uV64/job/Jbin_uV64__jsk_tilt_laser__ubuntu_vivid_amd64__binary/
 * http://build.ros.org/view/Ibin_uS32/job/Ibin_uS32__hokuyo_node__ubuntu_saucy_i386__binary/

**Comment by mikaelarguedas** [comment]
This failure showed up again, I rebased the `docker_fix_env_var` branch and triggered manually the Lunar jobs that were failing. I didn't check recent failures of the other distros to see if the same thing was needed there.

**Comment by tfoote** [comment]
Still an issue here: http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__diagnostic_aggregator__ubuntu_xenial_amd64__binary/25/

Another rebase and manual trigger. Here's to the new xenial based deployment coming soon!

**Pull request merged**
