### PR TITLE
release new version targeting hosts based on Xenial

### PR DESCRIPTION
**Pull request by jonazpiazu**
More info in this issue https://github.com/ros-infrastructure/ros_buildfarm/issues/507

### CODE REVIEW

**Comment by dirk-thomas** [comment]
This change also implies that the buildfarm you are creating would track `master` which I would rather not recommend. While we do our best to keep things stable some changes on the master branch might require changes to the deployment at the same time. So it is recommended to use the latest release unless you want to live on the bleeding edge...

**Comment by jonazpiazu** [comment]
The problem in my case is that there is no release for buildfarm_deployment and buildfarm_deployment_config, so I am using the master for the deployment.

But without the change for the ros_buildfarm version, I am not able to setup a working scenario, as the last tagged version of ros_buildfarm is not "compatible" with the master version of buildfarm_deployment.

So that is why I consider that this PR is relevant for anyone trying to deploy the buildfarm now.

**Comment by dirk-thomas** [comment]
Yes, this patch will help as a temporary workaround. But for the reason mentioned above I don't think it is sane "default" recommendation and therefore I won't merge it but keep it open for visibility until there is a new release of this package targeting Xenial.

**Comment by dirk-thomas** [comment]
Closing in favor of the referenced issue #507.

**Pull request closed without merging**
