### PR TITLE
Add mapping from OS names to packaging formats

### PR DESCRIPTION
**Pull request by cottsay**
~~At the moment, only the 'deb' package format is supported. However, this configuration option will enable plumbing for additional package formats moving forward.~~

I plan to follow this PR with other PRs which will take advantage of it on a case-by-case basis. Once the 'rpm' format is supported throughout the release jobs, I'll add it to the list of supported values for this option.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Isn't there a known mapping from targets to their packaging format? Do we need to specify the package format separately?

**Comment by cottsay** [comment]
The whole buildfarm only supports deb, so no. Deb is assumed everywhere.

Would you rather I set up mapping somewhere?

**Comment by dirk-thomas** [comment]
I am mostly wondering if this can be derived from existing configuration data. If yes, we should avoid adding a new option. If no, in which cases is the existing information not sufficient?

**Comment by cottsay** [comment]
I could set up a static mapping.

Since we need to use the packaging format to derive the meaning behind configuration values like repository URLs, we should probably enforce that it isn't possible to create a build file that covers both deb and rpm distros. I'll add an assert to ReleaseBuildFile to cover that.

Hang tight - I'll see what this looks like.

**Comment by cottsay** [comment]
> I could set up a static mapping.

Okay, let me know what you think of that approach.

**Comment by dirk-thomas** [comment]
The mapping looks fine. But why do it in the build file (which currently is a 1-to-1 representation of the yaml configuration)? I would suggest doing it where the build file is being used.

**Comment by cottsay** [comment]
> But why do it in the build file

Here is my thought process:
1. It needs to be in the config subdirectory so I can add an assertion to the build file to check if the user is trying to *cross the streams*.
2. The values which `package_format` determines the meaning of are all on the build file already. It many places we access those values, we'll need the context of what they mean.

**Comment by dirk-thomas** [comment]
> It needs to be in the config subdirectory so I can add an assertion to the build file to check if the user is trying to cross the streams.

Why can't that check be anywhere else?

**Comment by cottsay** [comment]
> Why can't that check be anywhere else?

Because I prefer doing things once instead of more than once, and I prefer errors to happen earlier rather than later.

This isn't worth the debating. I'll drop the assert and move it back to `common.py`, and I'll add asserts when I access the mapping in the future changes.

**Pull request merged**
