### PR TITLE
simplify logic

### PR DESCRIPTION
**Pull request by dirk-thomas**
See https://github.com/ros-infrastructure/ros_buildfarm/commit/f96ee6e1578838c2ba5763fbcc1de1d8ea33a514#commitcomment-16663472

### CODE REVIEW

**Comment by tfoote** [comment]
+1

**Comment by tfoote** [comment]
this was still on my todo list, thanks for cleaning it up. PS I've got a new generic generator for the images at https://github.com/osrf/ubuntu_32bit-docker/tree/generic which can let use produce them all. With it's current implementation it produces osrf/$os_$arch:$codename  I think it would make sense for use to homogenize the naming instead of adding a special case at both ends. also i386 is what upstream is prototyping with https://hub.docker.com/u/i386/

**Comment by tfoote** [comment]
Note that I need to extend this to debian arm64 jessie too 

I just extended the test farm to build debian arm64 but it's building amd64 debs right now due to this logic: http://54.183.26.131:8080/view/Kbin_arm_dJv8/job/Kbin_arm_dJv8__catkin__debian_jessie_arm64__binary/1/

**Comment by dirk-thomas** [comment]
Obsolete with #262 being merged.

**Pull request closed without merging**
