### PR TITLE
Add !relative_url YAML constructor

### PR DESCRIPTION
**Pull request by cottsay**
The purpose of this constructor is to support relative URL resolution in arbitrary locations in the buildfarm's configuration YAML. Some fields in the config already implicitly do this (such as the buildfile references from the index), but this will add support for any field to contain a relative URL.

Staging deployment: https://build.test.ros2.org/job/ci__infra_ubuntu_noble_amd64/

Example use: https://github.com/ros2/ros_buildfarm_config/blob/200fcfd96aceaf2d0791682a6b16e80a59669e52/global/ci-infra.yaml#L43-L44

### CODE REVIEW

**Review by nuclearsandwich — APPROVED** [review]
Ooh! I really like making this an explicit convention.

Do we need to document this somewhere or can we wait to documented in its expected use locations?

**Comment by cottsay** [comment]
Yeah, we should probably document this as well as `!include` somewhere.

I don't currently have a plan to transition the existing implicit URL resolutions to use this, but we could consider a follow-up change to deprecate them at some point.

**Comment by cottsay** [comment]
I added docs in the most recent changes. PTAL.

**Review by nuclearsandwich — APPROVED** [review]
Nice! Thanks for adding docs.

**Pull request merged**
