### PR TITLE
Install apt transport https

### PR DESCRIPTION
**Pull request by mikaelarguedas**
**WIP do not merge** opening for visibility and testing.
Alternative to https://github.com/ros-infrastructure/ros_buildfarm/pull/549

### CODE REVIEW

**Comment by dirk-thomas** [comment]
I updated the comment but isn't there a good chance that the installation will already fail when we hit a https mirror?

**Comment by mikaelarguedas** [comment]
> I updated the comment but isn't there a good chance that the installation will already fail when we hit a https mirror?

Yeah it should be done *before* the `sed` IMO.
We faced mirror issues (requiring the use of cloudfront) mostly for the additional components (nonfree contrib etc). So I would hope that the install before changing the mirror will work (but I dont have any number to back it ^^)

**Comment by clalancette** [comment]
I've deployed the updated version of this PR to 20 of the failing packages on the buildfarm using this command:

```
TZ=PST+08 generate_release_jobs.py https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml melodic ds --package-names xacro actionlib_tutorials audio_play diagnostic_analysis ecl_linear_algebra executive_smach filters hardware_interface message_filters qb_chain qb_device_utils robot_activity rosdiagnostic rosmon roswtf rqt_bag rqt_graph rqt_logger_level rqt_py_common rqt_robot_steering
```

All 20 of those that I reconfigured are now passing.  As an additional piece of data, many of the downstream packages (which were not reconfigured) are still failing.  So this definitely seems to be helping so far.

**Comment by clalancette** [comment]
All right, most of Melodic on Debian Stretch has rebuilt with this change, and seems much happier (Moveit is still building, but it will take a while).  Travis keeps failing; I haven't investigated it yet, though it seems unrelated.  Reviews are certainly welcome, then we can decide whether to merge with the failing CI or investigate it.

**Comment by dirk-thomas** [comment]
To be considered for merging the change to the version needs to be reverted.

With that commit CI will get retriggered anyway. If it stil fails please look into it since it will only get merged with a green CI. For spurious error you can always retrigger the Travis builds if necessary.

**Comment by mikaelarguedas** [comment]
Travis has been having connexion issues today. I experienced it on several repositories.

The last 5 travis run all failed at different times but all because of connection issue. Let's :crossed_fingers: for the new round build but if we don't get travis to pass I'd recommend merging before the nightlies anyway to get this deployed on all jobs.

Change looks good to me with the version reverted :+1:

**Pull request merged**
